// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// print_known_celltypes
void print_known_celltypes();
RcppExport SEXP _DACx_print_known_celltypes() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    print_known_celltypes();
    return R_NilValue;
END_RCPP
}
// fetch_cell_type_params
List fetch_cell_type_params(std::string type_name);
RcppExport SEXP _DACx_fetch_cell_type_params(SEXP type_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type type_name(type_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(fetch_cell_type_params(type_name));
    return rcpp_result_gen;
END_RCPP
}
// build_cell_type_from_list
void build_cell_type_from_list(const std::string& type_name, const List& params);
RcppExport SEXP _DACx_build_cell_type_from_list(SEXP type_nameSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type type_name(type_nameSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    build_cell_type_from_list(type_name, params);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_motif();
RcppExport SEXP _rcpp_module_boot_network();
RcppExport SEXP _rcpp_module_boot_Prj();

static const R_CallMethodDef CallEntries[] = {
    {"_DACx_print_known_celltypes", (DL_FUNC) &_DACx_print_known_celltypes, 0},
    {"_DACx_fetch_cell_type_params", (DL_FUNC) &_DACx_fetch_cell_type_params, 1},
    {"_DACx_build_cell_type_from_list", (DL_FUNC) &_DACx_build_cell_type_from_list, 2},
    {"_rcpp_module_boot_motif", (DL_FUNC) &_rcpp_module_boot_motif, 0},
    {"_rcpp_module_boot_network", (DL_FUNC) &_rcpp_module_boot_network, 0},
    {"_rcpp_module_boot_Prj", (DL_FUNC) &_rcpp_module_boot_Prj, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_DACx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
