# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_known_celltypes <- function() {
    invisible(.Call(`_DACx_print_known_celltypes`))
}

fetch_cell_type_params <- function(type_name) {
    .Call(`_DACx_fetch_cell_type_params`, type_name)
}

build_cell_type_from_list <- function(type_name, params) {
    invisible(.Call(`_DACx_build_cell_type_from_list`, type_name, params))
}

