# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_known_celltypes <- function() {
    invisible(.Call(`_DACx_print_known_celltypes`))
}

fetch_cell_type_params <- function(type_name) {
    .Call(`_DACx_fetch_cell_type_params`, type_name)
}

add_cell_type <- function(params) {
    invisible(.Call(`_DACx_add_cell_type`, params))
}

modify_cell_type <- function(type_name, params) {
    invisible(.Call(`_DACx_modify_cell_type`, type_name, params))
}

